# Generated by Django 5.2.4 on 2025-07-13 12:31

import utils.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=utils.utils.user_image_path, verbose_name='Аватар'),
        ),
    ]
