# Generated by Django 5.2.4 on 2025-07-16 09:39

import goods.storages_backends
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0002_remove_product_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, null=True, storage=goods.storages_backends.ProductImageStorage(), upload_to=goods.storages_backends.ProductImageStorage.image_path, verbose_name='Изображение'),
        ),
        migrations.AlterField(
            model_name='productimage',
            name='image',
            field=models.ImageField(storage=goods.storages_backends.ProductImageStorage(), upload_to=goods.storages_backends.ProductImageStorage.image_path, verbose_name='Изображение'),
        ),
    ]
