# Generated by Django 5.2.4 on 2025-07-16 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0003_alter_product_image_alter_productimage_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='sku',
            field=models.CharField(default='SKU-DEFAULT', max_length=100, verbose_name='Артикул'),
            preserve_default=False,
        ),
    ]
