# Generated by Django 5.2.4 on 2025-07-20 06:51

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0004_product_sku'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='slug',
            field=models.SlugField(default=django.utils.timezone.now, max_length=200, unique=True, verbose_name='URL'),
            preserve_default=False,
        ),
    ]
