# Generated by Django 5.2.4 on 2025-07-08 12:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0005_alter_products_image_productimage'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productimage',
            options={'ordering': ('id',), 'verbose_name': 'Изображение продукта', 'verbose_name_plural': 'Изображения продуктов'},
        ),
        migrations.AlterModelTable(
            name='productimage',
            table='product_image',
        ),
    ]
