# Generated by Django 5.2.4 on 2025-07-12 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0006_alter_productimage_options_alter_productimage_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='composition',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Состав'),
        ),
        migrations.AddField(
            model_name='products',
            name='country',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Страна'),
        ),
        migrations.AddField(
            model_name='products',
            name='firm',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Фирма'),
        ),
        migrations.AddField(
            model_name='products',
            name='sizes',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Размеры'),
        ),
    ]
