# Generated by Django 5.2.4 on 2025-07-20 09:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0006_tag_product_tags'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='tag',
            table='tag',
        ),
    ]
