# Generated by Django 5.2.4 on 2025-07-12 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0007_products_composition_products_country_products_firm_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='model',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Модель'),
        ),
    ]
