# Generated by Django 5.2.4 on 2025-07-20 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0008_firm_alter_product_firm'),
    ]

    operations = [
        migrations.AddField(
            model_name='productvariant',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Описание'),
        ),
    ]
