# Generated by Django 5.2.4 on 2025-08-01 07:49

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0009_productvariant_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='productvariant',
            name='color_code',
            field=models.CharField(blank=True, help_text='Например: #FF5733', max_length=7, null=True, validators=[django.core.validators.RegexValidator(message='Введите корректный HEX-код цвета', regex='^#(?:[0-9a-fA-F]{3}){1,2}$')], verbose_name='Код цвета'),
        ),
    ]
