# Generated by Django 5.2.4 on 2025-07-12 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_alter_order_options_alter_orderitem_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='is_paid',
        ),
        migrations.AlterField(
            model_name='order',
            name='requires_delivery',
            field=models.BooleanField(default=False, verbose_name='Требуется доставка'),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('pending', 'Ожидает оплату'), ('paid', 'Оплачен'), ('failed', 'Ошибка оплаты')], default='pending', max_length=20, verbose_name='Статус заказа'),
        ),
    ]
