# Generated by Django 5.2.4 on 2025-07-15 09:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_alter_orderitem_product'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderitem',
            old_name='product',
            new_name='ProductVariant',
        ),
    ]
