# Generated by Django 5.2.4 on 2025-07-15 09:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_rename_product_orderitem_productvariant'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderitem',
            old_name='ProductVariant',
            new_name='product_variant',
        ),
    ]
