# Generated by Django 5.2.4 on 2025-07-20 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_rename_productvariant_orderitem_product_variant'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='delivery_status',
            field=models.CharField(choices=[('processing', 'В обработке'), ('waiting_pickup', 'Ожидает в пункте выдачи')], default='processing', max_length=20, verbose_name='Статус доставки'),
        ),
    ]
