# Generated by Django 5.2.4 on 2025-07-20 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_order_delivery_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='delivery_status',
            field=models.CharField(choices=[('processing', 'В обработке'), ('waiting_pickup', 'Ожидает в пункте выдачи'), ('delivered', 'Товар доставлен')], default='processing', max_length=20, verbose_name='Статус доставки'),
        ),
    ]
