# Generated by Django 5.2.4 on 2025-08-03 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_alter_order_delivery_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='delivery_status',
            field=models.CharField(choices=[('processing', 'В обработке'), ('waiting_pickup', 'Ожидает в пункте выдачи'), ('delivered', 'Товар доставлен'), ('cancelled', 'Заказ отменён')], default='processing', max_length=20, verbose_name='Статус доставки'),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('pending', 'Ожидает оплату'), ('paid', 'Оплачено'), ('failed', 'Ошибка оплаты'), ('cancelled', 'Заказ отменён')], default='pending', max_length=20, verbose_name='Статус заказа'),
        ),
    ]
